# SPDX-FileCopyrightText: 2022 Contributors to the Power Grid Model project <dynamic.grid.calculation@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0
---
multipliers:
  .+_percent: 0.01
  .+_k(a|v|w): 1_000.0
  .+_m(w|va|var): 1_000_000.0
